---

 annotate_cnv:
   cnv_amp_genes:
     path: GMS560/cnv/cnv_amp_genes_240307.bed
     checksum: daa4bd789c9beb84bf1c02e125dd1fd6
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.6.0/cnv/cnv_amp_genes_240307.bed

   cnv_loh_genes_all: 
     path: GMS560/cnv/cnv_loh_genes_240618.bed
     checksum: de777ddcbee346f5a77e420ff88168fa
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.10.1/cnv/cnv_loh_genes_240618.bed
 
   cnv_loh_genes_validated: 
     path: GMS560/cnv/cnv_loh_uppsala_genes.bed
     checksum: 2f72bf8e05124335ffc2adf860cd13c8
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.1.1/cnv/cnv_loh_uppsala_genes.bed

 bcftools_filter_include_region:
   exon: 
     path: GMS560/design/pool1_pool2.sort.merged.padded20.cnv200.hg19.split_fusion_genes.MUC6_31_rm.exon_only.reannotated.230222.bed 
     checksum: c85f3369444cd6f27a397eef0a24fff9
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.1.1/design/pool1_pool2.sort.merged.padded20.cnv200.hg19.split_fusion_genes.MUC6_31_rm.exon_only.reannotated.230222.bed

 bcftools_filter_exclude_region:
   blacklist: 
     checksum: 0e6ad6718e87594732814608a595888b
     path: GMS560/cnv/cnvkit_germline_blacklist_20240613.bed
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.10.0/cnv/cnvkit_germline_blacklist_20240613.bed

 bcftools_id_snps:
   snps_bed: 
     checksum: ab9b7084d599606bb52142d26158f5e1
     path: GMS560/design/ID_SNPs.bed
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.1.1/design/ID_SNPs.bed
  
 call_small_cnv_amplifications:
   regions_file: 
     checksum: d276c7848ed8fecc034f76bfd815e537
     path: GMS560/cnv/cnv_amplification_genes_240307.tsv
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.6.0/cnv/cnv_amplification_genes_240307.tsv

 call_small_cnv_deletions:
   blacklist:
     checksum: 019763e1b79682a56074a3f53a73d149
     path: GMS560/cnv/small_deletions_caller_blacklist.tsv
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.7.0/cnv/small_deletions_caller_blacklist.tsv

   regions_file:
     checksum: e94adedc10b49b5a5a990ee0f938239d
     path: GMS560/cnv/cnv_deletion_genes_240618.tsv
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.10.1/cnv/cnv_deletion_genes_240618.tsv

 cnvkit_build_normal_reference:
   mappability:
     checksum: 5663ce9e7576e8ed7b4fa06fad1fdb88
     path: GMS560/cnv/access-5k-mappable.hg19.bed
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.6.0/cnv/access-5k-mappable.hg19.bed

 cnv_tsv_report:
   chrom_arm_size:
     checksum: 3b0242bea88285383dbb42aec1f252d0
     path: GMS560/cnv/chromosome_arm_size.tsv
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.6.0/cnv/chromosome_arm_size.tsv
     
 exon_skipping:
   design_bed:
     checksum: 7fe64299477aa4b6a5f5783cce9fa30f
     path: GMS560/design/Twist_RNA_Design5.annotated.bed
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.1.1/design/Twist_RNA_Design5.annotated.bed

 filter_fuseq_wes:
   gene_white_list:
     checksum: d762e65cc9d9d01d022db7de7c31cc68
     path: GMS560/fuseq_wes/fuseq_wes_gene_white_list.txt
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.1.1/fuseq_wes/fuseq_wes_gene_white_list.txt

   transcript_black_list:
     checksum: 586ad13ce609fdf5390d299cbbaae183
     path: GMS560/fuseq_wes/fuseq_wes_transcript_black_list.txt
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.1.1/fuseq_wes/fuseq_wes_transcript_black_list.txt

   gene_fusion_black_list:
     checksum: 21f8b965c1404f6ec4088d3816421809
     path: GMS560/fuseq_wes/false_positive_fusion_pairs.txt
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.4.0/fuseq_wes/false_positive_fusion_pairs.txt

 fuseq_wes:
   params:
     checksum: d2e6d449027c49e24f026261082fa5bb
     path: GMS560/fuseq_wes/fuseq_params.txt
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.1.1/fuseq_wes/fuseq_params.txt

 gatk_collect_allelic_counts:
   SNP_interval:
     checksum: 47cee8e04769d13e1c282fedf7333eac
     path: GMS560/cnv/gnomad_SNP_0.001_target.annotated.interval_list
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.1.1/cnv/gnomad_SNP_0.001_target.annotated.interval_list

 gene_fuse:
   genes: 
     checksum: c35fc6fbf81ce2e1cc55b536742ccf02
     path: GMS560/gene_fuse/GMS560_fusion_w_pool2.hg19.221117.csv
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.1.1/gene_fuse/GMS560_fusion_w_pool2.hg19.221117.csv

 hotspot_annotation:
   hotspots:
     checksum: 50564a9b99f86b123bb61f6e361eff10
     path: GMS560/reports/Hotspots_combined_regions_nodups.231011.csv
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.4.0/design/Hotspots_combined_regions_nodups.231011.csv

 hotspot_report:
   hotspot_mutations:
     checksum: 50564a9b99f86b123bb61f6e361eff10
     path: GMS560/reports/Hotspots_combined_regions_nodups.231011.csv
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.4.0/design/Hotspots_combined_regions_nodups.231011.csv
     
   hotspot_mutations_ENC:
     checksum: 3de80edc5f06fdaee55f0a302e20315a
     path: GMS560/reports/ENC_hotspots_240919.csv
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.11.0/design/ENC_hotspots_240919.csv

 jumble_reference:
   annotation_file1:
     checksum: 944896de8f6ab376459f8893598c780d
     path: GMS560/cnv/jumble_annotation/allexons.txt
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.11.0/cnv/jumble_annotation/allexons.txt

   annotation_file2:
     checksum: 5a986871cc991852d2135135db48711f
     path: GMS560/cnv/jumble_annotation/allgenes.txt
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.11.0/cnv/jumble_annotation/allgenes.txt

   annotation_file3:
     checksum: 5252c7462c8b0953a7832cc073415f0b
     path: GMS560/cnv/jumble_annotation/cancergenes.txt
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.11.0/cnv/jumble_annotation/cancergenes.txt

 manta_config_t:
   extra:
     checksum: b8f464f2af0d71c4e91fcdbd90378b6d
     path: GMS560/design/pool1_pool2.sort.merged.padded20.cnv200.hg19.split_fusion_genes.210608.bed.gz
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.1.1/design/pool1_pool2.sort.merged.padded20.cnv200.hg19.split_fusion_genes.210608.bed.gz
   extra_tbi:
     checksum: 05ebd6d103b6c40684de610c41cfffde
     path: GMS560/design/pool1_pool2.sort.merged.padded20.cnv200.hg19.split_fusion_genes.210608.bed.gz.tbi
     type: file        
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.1.1/design/pool1_pool2.sort.merged.padded20.cnv200.hg19.split_fusion_genes.210608.bed.gz.tbi

 merge_cnv_json:
   cytobands:
     checksum: 64de0499795484f1b70410a4cdd3d06f
     path: GMS560/cnv/cytoBand.hg19.txt
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.9.0/cnv/cytoBand.hg19.txt

 msisensor_pro_filter_sites:
   msi_sites_bed:
     checksum: 74c4fddf7928902c7b107673551b2c8b
     path: GMS560/design/SelectedMSIloci2019Sorted.bed
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.12.0/design/SelectedMSIloci2019Sorted.bed

 purecn:    
   intervals: 
     checksum: 0857e05962696cd3c2e5a4ea94d0fb2c
     path: GMS560/purecn/targets_twist-gms-st_hg19_25000_intervals.txt
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.1.1/cnv/targets_twist-gms-st_hg19_25000_intervals.txt

 purecn_coverage:
   intervals:
     checksum: 0857e05962696cd3c2e5a4ea94d0fb2c
     path: GMS560/purecn/targets_twist-gms-st_hg19_25000_intervals.txt
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.1.1/cnv/targets_twist-gms-st_hg19_25000_intervals.txt

 report_fusions:
   annotation_bed:
     checksum: af529c0ece5fe201de4d507000564ff7
     path: GMS560/design/Twist_RNA_fusionpartners.bed
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.1.1/rna_fusion/Twist_RNA_fusionpartners.bed

   fp_fusions: 
     checksum: 3886104b8c9c0c73ec8edb40b8d1428d
     path: GMS560/rna_fusion/filter_rna_fusions_20240923.txt
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.11.0/rna_fusion/filter_rna_fusions_20240923.txt

 references:
   design_bed:
     checksum: 06751f8685f1d507f4c48774450c0275
     path: GMS560/design/pool1_pool2.sort.merged.padded20.cnv200.hg19.split_fusion_genes.reannotated.230222.bed
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.1.1/design/pool1_pool2.sort.merged.padded20.cnv200.hg19.split_fusion_genes.reannotated.230222.bed

   design_intervals: 
     checksum: babb76d1e2490619eef47cf5b41db9f7
     path: GMS560/design/pool1_pool2.sort.merged.padded20.cnv200.hg19.split_fusion_genes.MUC6_31_rm.exon_only.reannotated.210608.interval_list
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.1.1/design/pool1_pool2.sort.merged.padded20.cnv200.hg19.split_fusion_genes.MUC6_31_rm.exon_only.reannotated.210608.interval_list
    
   design_intervals_gatk_cnv: 
     checksum: 812f9f89faf750d1948f19166056f1d1
     path: GMS560/design/pool1_pool2_nochr_3c.sort.merged.padded20.cnv400.hg19.210311.met.annotated.bed.preprocessed.interval_list
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.1.1/design/pool1_pool2_nochr_3c.sort.merged.padded20.cnv400.hg19.210311.met.annotated.bed.preprocessed.interval_list
  
   design_intervals_rna:
     checksum: 5e38c3495625d3f854859eddf1643ff7
     path: GMS560/design/Twist_RNA_Design5.annotated.20230630.interval_list
     type: file
     url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.4.1/design/Twist_RNA_Design5.annotated.20230630.interval_list

 report_gene_fuse:
   filter_fusions:
      checksum: b6bc58f14e2cee6e481f1cabf1fd2c0b
      path: GMS560/gene_fuse/filter_fusions_20230214.csv
      type: file
      url: https://github.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/raw/v0.1.1/gene_fuse/filter_fusions_20230214.csv

 tmb:
   filter_genes:
      checksum: c1a958320451fab1200ab769d963d4c6
      path: GMS560/tmb/tmb_filter_genes.txt
      type: file
      url: https://raw.githubusercontent.com/genomic-medicine-sweden/Twist_Solid_pipeline_files/v0.2.1/tmb/tmb_filter_genes.txt
