---
 svdb_query:
   db_string:
     checksum: 076f3a9bec5e9941eb4bbbf4594c0037
     path: GMS560/PoN/SVDB/all_TN_292_svdb_0.8_20220505.vcf
     type: file
     url: https://figshare.scilifelab.se/ndownloader/files/40882898

 purecn:
   extra: 
     checksum: eb311461a92b53a9494bba9625ecd4c3
     path: GMS560/PoN/purecn/mapping_bias_nextseq_27_hg19.rds
     type: file
     url: https://figshare.scilifelab.se/ndownloader/files/40882865
   extra_novaseqX:
     checksum: a793888e88fe232035b4718cc76c4f39
     path: GMS560/PoN/purecn/mapping_bias_novaseqX_24_updated.rds
     type: file
     url: https://figshare.com/ndownloader/files/60373421?private_link=88202740beb6fcbac09d
   extra_cfDNA_novaseqX:
     checksum: 902aa5b26713d0c74ef40ba2ccd528c4
     path: GMS560/PoN/purecn/mapping_bias_cfDNA_novaseqX_24.rds
     type: file
     url: https://figshare.com/ndownloader/files/60373412?private_link=88202740beb6fcbac09d

   normaldb:
     checksum: d77528e5bfeec40791235e52dcbed7ef
     path: GMS560/PoN/purecn/normalDB_nextseq_27_hg19.rds
     type: file
     url: https://figshare.scilifelab.se/ndownloader/files/40882874
   normaldb_novaseqX:
     checksum: 7776f1f73299370bb13f272e93e12c37
     path: GMS560/PoN/purecn/normalDB_novaseqX_24_updated.rds
     type: file
     url: https://figshare.com/ndownloader/files/60373427?private_link=88202740beb6fcbac09d
   normaldb_cfDNA_novaseqX:
     checksum: 22426218b6a6e629a7168875f0f2fcdc
     path: GMS560/PoN/purecn/normalDB_cfDNA_novaseqX_24.rds
     type: file
     url: https://figshare.com/ndownloader/files/60373424?private_link=88202740beb6fcbac09d


 gatk_denoise_read_counts:
   normal_reference:
      checksum: ab0a2f3276125c8695b72a2b2c5779ea
      path: GMS560/PoN/gatk_cnv_novaseq_13.hdf5
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/40882862
   normal_reference_novaseqX:
      checksum: da197d7aa245c6d7bd423cc7b292cf37
      path: GMS560/PoN/gatk_cnv_novaseqX_24_updated.hdf5
      type: file
      url: https://figshare.com/ndownloader/files/60373466?private_link=88202740beb6fcbac09d
   normal_reference_cfDNA_novaseqX:
      checksum: 485ab1af7d010186793d13aff35e6b1e
      path: GMS560/PoN/gatk_cnv_cfDNA_novaseqX_24.hdf5
      type: file
      url: https://figshare.com/ndownloader/files/60373457?private_link=88202740beb6fcbac09d

 cnvkit_batch:
   normal_reference:
     checksum: 203d8e695b6324f8a5c27e2c7882f3d2
     path: GMS560/PoN/cnvkit_PoN_combined_hg19.cnn
     type: file
     url: https://figshare.com/ndownloader/files/46640134?private_link=88202740beb6fcbac09d
   normal_reference_novaseqX:
      checksum: de50b7d3a00796e6115c7c6bac268659
      path: GMS560/PoN/cnvkit_novaseqX_24_updated.cnn
      type: file
      url: https://figshare.com/ndownloader/files/60373469?private_link=88202740beb6fcbac09d
   normal_reference_cfDNA_novaseqX:
      checksum: 4ea6bfd10711e952b6fb22d1365ea177
      path: GMS560/PoN/cnvkit_cfDNA_novaseqX_24.cnn
      type: file
      url: https://figshare.com/ndownloader/files/60373460?private_link=88202740beb6fcbac09d

 cnvkit_batch_hrd:
   normal_reference_hrd:
      checksum: e7853030e7a6b0ccbeffb7c008983a29
      path: GMS560/PoN/cnvkit_novaseq_13_HRD.cnn
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/40914854

 jumble_run:
   normal_reference:
     checksum: 3add115d1471c3055d7984e3baea0364
     path: GMS560/PoN/jumble.combined.filtered.50.PoN.hg19.RDS
     type: file
     url: https://figshare.com/ndownloader/files/49365301?private_link=88202740beb6fcbac09d
   normal_reference_novaseqX:
      checksum: 0f513e596e78473c1dc424bf7c53c783
      path: GMS560/PoN/jumble_novaseqX_24_updated.RDS
      type: file
      url: https://figshare.com/ndownloader/files/60373496?private_link=88202740beb6fcbac09d
   normal_reference_cfDNA_novaseqX:
      checksum: f61777975b6ccc010c9ec5fe87f2ff11
      path: GMS560/PoN/jumble_cfDNA_novaseqX_24.RDS
      type: file
      url: https://figshare.com/ndownloader/files/60373493?private_link=88202740beb6fcbac09d

 msisensor_pro_filter_sites:
   PoN:
     checksum: 40bda778c9208a366b39ec0e6cefde11
     path: GMS560/PoN/Msisensor_pro_reference_novaseq_13.list_baseline
     type: file
     url: https://figshare.scilifelab.se/ndownloader/files/40882871
   PoN_novaseqX:
      checksum: 2f6f7b35f34bd645772c9c3552160723
      path: GMS560/PoN/Msisensor_pro_reference_novaseqX_24_updated.list_baseline
      type: file
      url: https://figshare.com/ndownloader/files/60373463?private_link=88202740beb6fcbac09d
   PoN_cfDNA_novaseqX:
      checksum: d80852f80537040d0a6cb5d47f141304
      path: GMS560/PoN/Msisensor_pro_reference_cfDNA_novaseqX_24.list_baseline
      type: file
      url: https://figshare.com/ndownloader/files/60373454?private_link=88202740beb6fcbac09d

 reference:
    background:
      checksum: 563aa06990d90ed3ef33b4da1aac3c2e
      path: GMS560/Background/background_panel_novaseq_13_dp500_af015.tsv
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/40882844
    background_novaseqX:
      checksum: db686c06b0741ceb20efa454559484be
      path: GMS560/Background/background_panel_novaseqX_24_updated.tsv
      type: file
      url: https://figshare.com/ndownloader/files/60373409?private_link=88202740beb6fcbac09d
    background_cfDNA_novaseqX:
      checksum: 9bad8c5c96410be85d2165210893326e
      path: GMS560/Background/background_panel_cfDNA_novaseqX_24.tsv
      type: file
      url: https://figshare.com/ndownloader/files/60373403?private_link=88202740beb6fcbac09d
    
    artifacts: 
      checksum: 6d589735a4b922a6f7e852539f44a539
      path: GMS560/Artifact/artifact_panel_novaseq_13.tsv
      type: file
      url: https://figshare.scilifelab.se/ndownloader/files/40882838
    artifacts_novaseqX:
      checksum: 76647f5a454a4bd5c5fc26b1fd20931b
      path: GMS560/Artifact/artifact_panel_novaseqX_24_updated.tsv
      type: file
      url: https://figshare.com/ndownloader/files/60373400?private_link=88202740beb6fcbac09d
    artifacts_cfDNA_novaseqX:
      checksum: 43ff954120de7da4002f14064d2c40bf
      path: GMS560/Artifact/artifact_panel_cfDNA_novaseqX_24.tsv
      type: file
      url: https://figshare.com/ndownloader/files/60373358?private_link=88202740beb6fcbac09d
      

