jobs: 100
drmaa: " -A wp1 -N 1-1 -t {resources.time} -n {resources.threads} --mem={resources.mem_mb} --mem-per-cpu={resources.mem_per_cpu} --mem-per-cpu={resources.mem_per_cpu} --partition={resources.partition}"
default-resources: [threads=1, time="04:00:00", partition="low", mem_mb="1024", mem_per_cpu="3074"]
