filters:
  dp:
    description: "Soft filter variants with low coverage (DP lower than 100)"
    expression: "FORMAT:DP < 100"
    soft_filter_flag: "DP_lt_100"
    soft_filter: "True"
  vaf:
    description: "Soft filter variants with low vaf (AF lower than 0.05)"
    expression: "(FORMAT:AF:0 < 0.05 and !exist[1-hotspot, INFO:Hotspot])"
    soft_filter_flag: "AF_lt_0.05"
    soft_filter: "True"
  vaf_hotspot:
    description: "Soft filter hotspot variants with low vaf (AF lower than 0.01)"
    expression: "(FORMAT:AF:0 < 0.01 and exist[1-hotspot, INFO:Hotspot])"
    soft_filter_flag: "AF_HS_lt_0.01"
    soft_filter: "True"
  ad:
    description: "Soft filter variants with few observations (AD lower than 20)"
    expression: "(FORMAT:AD:1 < 20 and !exist[1-hotspot, INFO:Hotspot] and VEP:Gene != TERT)"
    soft_filter_flag: "AD_lt_20"
    soft_filter: "True"
  ad_hotspot:
    description: "Soft filter hotspot variants with few observations (AD lower than 10)"
    expression: "(FORMAT:AD:1 < 10 and exist[1-hotspot, INFO:Hotspot] and VEP:Gene != TERT)"
    soft_filter_flag: "AD_HS_lt_10"
    soft_filter: "True"
  ad_TERT:
    description: "Soft filter TERT variants with few observations (AD lower than 4)"
    expression: "(FORMAT:AD:1 < 4 and exist[1-hotspot, INFO:Hotspot] and VEP:Gene = TERT)"
    soft_filter_flag: "AD_TERT_lt_4"
    soft_filter: "True"
  germline:
    description: "Soft filter germline SNVs based on GnomAD"
    expression: "(VEP:gnomAD_AF > 0.00001 and !exist[COSV_[0-9]+, VEP:Existing_variation])"
    soft_filter_flag: "Germline"
    soft_filter: "True"
  artifacts:
    description: "Soft filter variants found in more than 2 normal samples"
    expression: "(INFO:Artifact:0 > 2 or INFO:Artifact:1 > 2)"
    soft_filter_flag: "Artifact_gt_2"
    soft_filter: "True"
  background:
    description: "Soft filter position with where backgound distribution overlaps variant (lower than 4 SD from median)"
    expression: "INFO:PositionNrSD < 4"
    soft_filter_flag: "Background_lt_4"
    soft_filter: "True"
