filters:
  vaf:
    description: "Hard filter variants with low vaf (AF lower than 0.05)"
    expression: "(FORMAT:AF:0 < 0.05 and !exist[1-hotspot, INFO:Hotspot])"
    soft_filter: "False"
  vaf_hotspot:
    description: "Hard filter hotspot variants with low vaf (AF lower than 0.01)"
    expression: "(FORMAT:AF:0 < 0.01 and exist[1-hotspot, INFO:Hotspot])"
    soft_filter: "False"
  artifacts:
    description: "Hard filter variants found in more than 3 normal samples"
    expression: "(INFO:Artifact:0 > 3 or INFO:Artifact:1 > 3)"
    soft_filter: "False"
  background:
    description: "Hard filter position with where backgound distribution overlaps variant (lower than 4 SD from median)"
    expression: "INFO:PositionNrSD < 4"
    soft_filter: "False"
  germline:
    description: "Hard filter germline"
    expression: "(VEP:gnomAD_AF > 0.00001 and !exist[COSV_[0-9]+, VEP:Existing_variation])"
    soft_filter: "False"
  ad:
    description: "Hard filter variants with few observations (AD lower than 20)"
    expression: "(FORMAT:AD:1 < 20 and !exist[1-hotspot, INFO:Hotspot] and VEP:SYMBOL != TERT)"
    soft_filter: "False"
  ad_hotspot:
    description: "Hard filter hotspot variants with few observations (AD lower than 10)"
    expression: "(FORMAT:AD:1 < 10 and exist[1-hotspot, INFO:Hotspot] and VEP:SYMBOL != TERT)"
    soft_filter: "False"
  ad_TERT:
    description: "Hard filter TERT variants with few observations (AD lower than 4)"
    expression: "(FORMAT:AD:1 < 4 and exist[1-hotspot, INFO:Hotspot] and VEP:SYMBOL = TERT)"
    soft_filter: "False"
