default_resources:
  threads: 1
  time: "4:00:00"
  mem_mb: 1024
  mem_per_cpu: 3072
  partition: low

cnvkit_build_normal_reference:
  threads: 20
  time: "8:00:00"

msisensor_pro_baseline:
  threads: 2
  time: "8:00:00"
