filters:
  germline:
    description: "Hard filter germline"
    expression: "(VEP:gnomAD_AF < 0.001)"
    soft_filter: "False"
  ad:
    description: "Hard filter variants with few observations (AD lower than 20)"
    expression: "(FORMAT:AD:1 < 20 or FORMAT:AD:0 < 20)"
    soft_filter: "False"
  snp_type:
    description: "Hard filter variants that are not SNVs"
    expression: "(!exist[SNV, VEP:VARIANT_CLASS])"
    soft_filter: "False"