filters:
  germline:
    description: "Hard filter germline"
    expression: "(VEP:gnomAD_AF > 0.005)"
    soft_filter: "False"
  ad:
    description: "Hard filter variants with few observations (AD lower than 20)"
    expression: "(FORMAT:AD:1 < 20 or FORMAT:AD:0 < 20)"
    soft_filter: "False"